import {Link} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowDown,ArrowRight,Compass,Headphones,Heart,Hotel,MapPin,MessageCircle,Plane,ShieldCheck,Sparkles,Users} from 'lucide-react';
import {contact} from '../data/content';

const reveal={initial:{opacity:0,y:45},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.2},transition:{duration:.8,ease:[.22,1,.36,1] as const}};
const values=[[Compass,'Curated with purpose','Every route, stay and experience earns its place.'],[Heart,'Personal by design','Your pace, interests and comfort shape the journey.'],[ShieldCheck,'Honest at every step','Clear advice, thoughtful value and dependable coordination.'],[Headphones,'Close throughout','Real support before, during and after your holiday.']] as const;

export default function About(){return <div className="overflow-hidden bg-[#071d33] text-white"><Hero/><Story/><Values/><Journey/><CTA/></div>}

function Hero(){return <section className="relative min-h-[820px] overflow-hidden"><motion.img initial={{scale:1.12}} animate={{scale:1}} transition={{duration:2,ease:[.22,1,.36,1]}} src="/images/hero/europe.jpg" alt="A Kakani Holidays journey" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,20,34,.94)_0%,rgba(4,20,34,.62)_48%,rgba(4,20,34,.15)_100%)]"/><div className="absolute inset-0 bg-gradient-to-t from-[#071d33] via-transparent to-[#071d33]/25"/><div className="lux-container relative flex min-h-[820px] items-center pt-24"><motion.div initial={{opacity:0,y:55}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.2}} className="max-w-4xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.2em] backdrop-blur-xl"><Sparkles size={13} className="text-[#e7b753]"/> The Kakani story</span><h1 className="mt-7 font-serif text-6xl leading-[.9] sm:text-7xl lg:text-[7.5rem]">Travel should<br/><em className="text-[#e7b753]">move you.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-white/65 md:text-lg">We create personal journeys that feel effortless, considered and alive from the first idea to the final return.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/customised-tours" className="lux-btn-gold">Shape my journey <ArrowRight size={16}/></Link><a href="#our-story" className="lux-btn-outline">Our story <ArrowDown size={16}/></a></div></motion.div><motion.div initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} transition={{delay:.65,duration:.9}} className="absolute bottom-12 right-[5%] hidden w-64 rounded-[26px] border border-white/20 bg-white/10 p-5 backdrop-blur-xl lg:block"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#e7b753]">Host of Happiness</p><div className="mt-5 grid grid-cols-2 gap-4"><Metric value="10K+" label="Tours"/><Metric value="30K+" label="Travellers"/></div></motion.div></div></section>}

function Story(){return <section id="our-story" className="relative bg-[#f4efe5] py-24 text-navy md:py-32"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_80%_20%,rgba(33,182,168,.18),transparent_55%)]"/><div className="lux-container relative grid gap-14 lg:grid-cols-12 lg:items-center"><motion.div {...reveal} className="lg:col-span-5"><p className="lux-eyebrow">Who we are</p><h2 className="mt-5 font-serif text-5xl leading-[.95] md:text-7xl">Not a booking desk.<br/><em className="text-sunset">Your travel partner.</em></h2><p className="mt-7 max-w-lg text-base leading-8 text-slate-600">Kakani Holidays brings thoughtful planning, honest value and human support together for domestic and international travel.</p><div className="mt-8 grid grid-cols-2 gap-3">{[['Domestic & international',Plane],['Custom holidays',Sparkles],['Handpicked stays',Hotel],['Guided experiences',MapPin]].map(([label,Icon])=><motion.div whileHover={{y:-5}} key={String(label)} className="rounded-2xl border border-navy/10 bg-white/70 p-4 backdrop-blur"><Icon className="text-sunset" size={19}/><p className="mt-3 text-xs font-extrabold">{String(label)}</p></motion.div>)}</div></motion.div><div className="relative min-h-[620px] lg:col-span-7"><motion.div initial={{clipPath:'inset(100% 0 0 0)'}} whileInView={{clipPath:'inset(0% 0 0 0)'}} viewport={{once:true}} transition={{duration:1.1,ease:[.22,1,.36,1]}} className="absolute left-0 top-0 h-[520px] w-[78%] overflow-hidden rounded-[48px]"><img src="/images/story/travel.jpg" alt="A thoughtfully designed holiday" className="h-full w-full object-cover transition duration-1000 hover:scale-105"/></motion.div><motion.div initial={{opacity:0,scale:.8,y:30}} whileInView={{opacity:1,scale:1,y:0}} viewport={{once:true}} transition={{delay:.45,duration:.8}} className="absolute bottom-0 right-0 w-[47%] overflow-hidden rounded-[34px] border-[8px] border-[#f4efe5] shadow-2xl"><img src="/images/story/team.jpg" alt="Kakani Holidays travel team" className="h-72 w-full object-cover"/></motion.div><motion.div animate={{y:[0,-12,0]}} transition={{duration:4,repeat:Infinity,ease:'easeInOut'}} className="absolute bottom-20 left-8 rounded-2xl bg-[#071d33] px-5 py-4 text-white shadow-xl"><p className="text-[9px] uppercase tracking-widest text-[#e7b753]">Our promise</p><p className="mt-1 font-serif text-xl">Every detail, considered.</p></motion.div></div></div></section>}

function Values(){return <section className="relative py-24 md:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_50%,rgba(0,109,156,.22),transparent_35%),radial-gradient(circle_at_90%_30%,rgba(255,122,69,.14),transparent_32%)]"/><div className="lux-container relative"><motion.div {...reveal} className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="lux-eyebrow !text-[#e7b753]">The Kakani difference</p><h2 className="mt-4 max-w-3xl font-serif text-5xl leading-[.95] md:text-7xl">The way we travel<br/>says everything.</h2></div><p className="max-w-sm text-sm leading-7 text-white/55">Premium is not excess. It is the confidence that every meaningful detail has been handled.</p></motion.div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{values.map(([Icon,title,copy],i)=><motion.article initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.12,duration:.7}} whileHover={{y:-10}} key={title} className="group min-h-[300px] rounded-[30px] border border-white/10 bg-white/[.055] p-7 backdrop-blur-xl"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e7b753] text-navy transition group-hover:rotate-6"><Icon size={23}/></span><h3 className="mt-10 font-serif text-2xl">{title}</h3><p className="mt-4 text-sm leading-7 text-white/50">{copy}</p></motion.article>)}</div></div></section>}

function Journey(){const steps=[['Listen','We start with how you want the holiday to feel.'],['Curate','Destinations, stays and moments are shaped around you.'],['Refine','We clarify every detail before you confirm.'],['Travel','Our team stays close while you enjoy the journey.']];return <section className="bg-[#e8b353] py-24 text-navy md:py-32"><div className="lux-container"><motion.div {...reveal} className="max-w-4xl"><p className="lux-eyebrow">How we work</p><h2 className="mt-4 font-serif text-5xl leading-[.95] md:text-7xl">From first thought<br/>to favourite memory.</h2></motion.div><div className="mt-16 grid gap-px overflow-hidden rounded-[32px] bg-navy/15 md:grid-cols-4">{steps.map(([title,copy],i)=><motion.article initial={{opacity:0,x:-25}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.12}} key={title} className="group bg-[#edbd62] p-7 transition hover:bg-[#f4ca78]"><h3 className="font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-navy/65">{copy}</p><ArrowRight className="mt-8 transition group-hover:translate-x-2"/></motion.article>)}</div></div></section>}

function CTA(){return <section className="relative min-h-[620px] overflow-hidden"><motion.img whileInView={{scale:1.06}} transition={{duration:8}} src="/images/story/cta.jpg" alt="Begin your next journey" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#071d33]/95 via-[#071d33]/60 to-transparent"/><div className="lux-container relative flex min-h-[620px] items-center"><motion.div {...reveal} className="max-w-4xl"><p className="lux-eyebrow !text-[#e7b753]">Your story starts here</p><h2 className="mt-5 font-serif text-6xl leading-[.92] md:text-8xl">Where would you<br/><em className="text-[#e7b753]">love to go?</em></h2><div className="mt-9 flex flex-wrap gap-3"><Link to="/packages" className="lux-btn-gold">Explore packages <ArrowRight size={16}/></Link><a href={`https://wa.me/${contact.phoneRaw}`} target="_blank" rel="noreferrer" className="lux-btn-outline"><MessageCircle size={17}/> Talk to us</a></div></motion.div></div></section>}

function Metric({value,label}:{value:string;label:string}){return <div><strong className="font-serif text-3xl text-[#e7b753]">{value}</strong><span className="mt-1 block text-[9px] uppercase tracking-widest text-white/50">{label}</span></div>}
